In [1]:
import pandas as pd
path="D:\\Desktop\\2023_24projects\\2023_projects\\20_heartdiseasepredictionclassification\\heart_disease.csv"
data=pd.read_csv(path)
print(data)
print(data.info())

       HeartDisease    BMI Smoking AlcoholDrinking Stroke  PhysicalHealth  \
0                No  16.60     Yes              No     No             3.0
1                No  20.34      No              No    Yes             0.0
2                No  26.58     Yes              No     No            20.0
3                No  24.21      No              No     No             0.0
4                No  23.71      No              No     No            28.0
...             ...    ...     ...             ...    ...             ...
319790          Yes  27.41     Yes              No     No             7.0
319791           No  29.84     Yes              No     No             0.0
319792           No  24.24      No              No     No             0.0
319793           No  32.81      No              No     No             0.0
319794           No  46.56      No              No     No             0.0

        MentalHealth DiffWalking     Sex  AgeCategory      Race Diabetic  \
0               30.0          No  Female        55-59     White      Yes
1                0.0          No  Female  80 or older     White       No
2               30.0          No    Male        65-69     White      Yes
3                0.0          No  Female        75-79     White       No
4                0.0         Yes  Female        40-44     White       No
...              ...         ...     ...          ...       ...      ...
319790           0.0         Yes    Male        60-64  Hispanic      Yes
319791           0.0          No    Male        35-39  Hispanic       No
319792           0.0          No  Female        45-49  Hispanic       No
319793           0.0          No  Female        25-29  Hispanic       No
319794           0.0          No  Female  80 or older  Hispanic       No

       PhysicalActivity  GenHealth  SleepTime Asthma KidneyDisease SkinCancer
0                   Yes  Very good        5.0    Yes            No        Yes
1                   Yes  Very good        7.0     No            No         No
2                   Yes       Fair        8.0    Yes            No         No
3                    No       Good        6.0     No            No        Yes
4                   Yes  Very good        8.0     No            No         No
...                 ...        ...        ...    ...           ...        ...
319790               No       Fair        6.0    Yes            No         No
319791              Yes  Very good        5.0    Yes            No         No
319792              Yes       Good        6.0     No            No         No
319793               No       Good       12.0     No            No         No
319794              Yes       Good        8.0     No            No         No

[319795 rows x 18 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(4), object(14)
memory usage: 43.9+ MB
None

In [2]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  object
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  object
 3   AlcoholDrinking   319795 non-null  object
 4   Stroke            319795 non-null  object
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  object
 8   Sex               319795 non-null  object
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  object
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  object
 16  KidneyDisease     319795 non-null  object
 17  SkinCancer        319795 non-null  object
dtypes: float64(4), object(14)
memory usage: 43.9+ MB

In [3]:
d = {'Yes':1,'No':0}
data["HeartDisease"]=data["HeartDisease"].map(d).fillna(data["HeartDisease"])

data["Smoking"]=data["Smoking"].map(d).fillna(data["Smoking"])

data["AlcoholDrinking"]=data["AlcoholDrinking"].map(d).fillna(data["AlcoholDrinking"])

data["Stroke"]=data["Stroke"].map(d).fillna(data["Stroke"])

data["DiffWalking"]=data["DiffWalking"].map(d).fillna(data["DiffWalking"])

data["Diabetic"]=data["Diabetic"].map(d).fillna(data["Diabetic"])

data["PhysicalActivity"]=data["PhysicalActivity"].map(d).fillna(data["PhysicalActivity"])

data["Asthma"]=data["Asthma"].map(d).fillna(data["Asthma"])

data["KidneyDisease"]=data["KidneyDisease"].map(d).fillna(data["KidneyDisease"])

data["SkinCancer"]=data["SkinCancer"].map(d).fillna(data["SkinCancer"])

In [4]:
data
d = {'male':1,'female':0}
data["Sex"]=data["Sex"].map(d).fillna(data["Sex"])

In [5]:
d = {'Male':1,'Female':0}
data["Sex"]=data["Sex"].map(d).fillna(data["Sex"])

In [6]:
f={'White':0,'Hispanic':1}
data["Race"]=data["Race"].map(f).fillna(data["Race"])

In [7]:
g={'Very good':0,'Fair':1,'Good':2}
data["GenHealth"]=data["GenHealth"].map(g).fillna(data["GenHealth"])

In [8]:
data

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,AgeCategory,Race,Diabetic,PhysicalActivity,GenHealth,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3.0,30.0,0,0,55-59,0.0,1.0,1,0.0,5.0,1,0,1
1,0,20.34,0,0,1,0.0,0.0,0,0,80 or older,0.0,0.0,1,0.0,7.0,0,0,0
2,0,26.58,1,0,0,20.0,30.0,0,1,65-69,0.0,1.0,1,1.0,8.0,1,0,0
3,0,24.21,0,0,0,0.0,0.0,0,0,75-79,0.0,0.0,0,2.0,6.0,0,0,1
4,0,23.71,0,0,0,28.0,0.0,1,0,40-44,0.0,0.0,1,0.0,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7.0,0.0,1,1,60-64,1.0,1.0,0,1.0,6.0,1,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,35-39,1.0,0.0,1,0.0,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,45-49,1.0,0.0,1,2.0,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,25-29,1.0,0.0,0,2.0,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,80 or older,1.0,0.0,1,2.0,8.0,0,0,0

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 18 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  int64
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  int64
 3   AlcoholDrinking   319795 non-null  int64
 4   Stroke            319795 non-null  int64
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  int64
 8   Sex               319795 non-null  int64
 9   AgeCategory       319795 non-null  object
 10  Race              319795 non-null  object
 11  Diabetic          319795 non-null  object
 12  PhysicalActivity  319795 non-null  int64
 13  GenHealth         319795 non-null  object
 14  SleepTime         319795 non-null  float64
 15  Asthma            319795 non-null  int64
 16  KidneyDisease     319795 non-null  int64
 17  SkinCancer        319795 non-null  int64
dtypes: float64(4), int64(10), object(4)
memory usage: 43.9+ MB

In [10]:
data.describe()

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,SkinCancer
count,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.00000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000,319795.000000
mean,0.085595,28.325399,0.412477,0.068097,0.037740,3.37171,3.898366,0.138870,0.475273,0.775362,7.097075,0.134061,0.036833,0.093244
std,0.279766,6.356100,0.492281,0.251912,0.190567,7.95085,7.955235,0.345812,0.499389,0.417344,1.436007,0.340718,0.188352,0.290775
min,0.000000,12.020000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000
25%,0.000000,24.030000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,6.000000,0.000000,0.000000,0.000000
50%,0.000000,27.340000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.000000,7.000000,0.000000,0.000000,0.000000
75%,0.000000,31.420000,1.000000,0.000000,0.000000,2.00000,3.000000,0.000000,1.000000,1.000000,8.000000,0.000000,0.000000,0.000000
max,1.000000,94.850000,1.000000,1.000000,1.000000,30.00000,30.000000,1.000000,1.000000,1.000000,24.000000,1.000000,1.000000,1.000000

In [11]:
data=data.drop(['AgeCategory','Race','Diabetic','GenHealth'],axis=1)

In [12]:
data

,HeartDisease,BMI,Smoking,AlcoholDrinking,Stroke,PhysicalHealth,MentalHealth,DiffWalking,Sex,PhysicalActivity,SleepTime,Asthma,KidneyDisease,SkinCancer
0,0,16.60,1,0,0,3.0,30.0,0,0,1,5.0,1,0,1
1,0,20.34,0,0,1,0.0,0.0,0,0,1,7.0,0,0,0
2,0,26.58,1,0,0,20.0,30.0,0,1,1,8.0,1,0,0
3,0,24.21,0,0,0,0.0,0.0,0,0,0,6.0,0,0,1
4,0,23.71,0,0,0,28.0,0.0,1,0,1,8.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
319790,1,27.41,1,0,0,7.0,0.0,1,1,0,6.0,1,0,0
319791,0,29.84,1,0,0,0.0,0.0,0,1,1,5.0,1,0,0
319792,0,24.24,0,0,0,0.0,0.0,0,0,1,6.0,0,0,0
319793,0,32.81,0,0,0,0.0,0.0,0,0,0,12.0,0,0,0
319794,0,46.56,0,0,0,0.0,0.0,0,0,1,8.0,0,0,0

In [13]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 319795 entries, 0 to 319794
Data columns (total 14 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   HeartDisease      319795 non-null  int64
 1   BMI               319795 non-null  float64
 2   Smoking           319795 non-null  int64
 3   AlcoholDrinking   319795 non-null  int64
 4   Stroke            319795 non-null  int64
 5   PhysicalHealth    319795 non-null  float64
 6   MentalHealth      319795 non-null  float64
 7   DiffWalking       319795 non-null  int64
 8   Sex               319795 non-null  int64
 9   PhysicalActivity  319795 non-null  int64
 10  SleepTime         319795 non-null  float64
 11  Asthma            319795 non-null  int64
 12  KidneyDisease     319795 non-null  int64
 13  SkinCancer        319795 non-null  int64
dtypes: float64(4), int64(10)
memory usage: 34.2 MB

In [14]:
X=data.drop('HeartDisease',axis=1)
y=data.HeartDisease

In [15]:
y = data.HeartDisease.ravel()

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.1)
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train = sc.fit_transform(X_train)
X_test= sc.transform(X_test)
from sklearn.svm import SVC
model=SVC()
model.fit(X_train, y_train)
model.score(X_test, y_test)

C:\Users\SAGAR\anaconda3\lib\site-packages\scipy\__init__.py:146: UserWarning: A NumPy version >=1.16.5 and <1.23.0 is required for this version of SciPy (detected version 1.26.2
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [ ]:
model.predict([[16.60,1,0,0,3.0,30.0,0,0,1,5.0,1,0,1]])